### ISSUE TITLE
Add characters

### ISSUE THREAD

**Issue by choron634** [shortintern2020-C-cryptograph/TeamE#5]
- [x] キャラクターの作成
- [x] アニメーション
- [x] idの振り分け

**Comment by monado3** [comment]
@choron634 
よく見ずmergeしてしまったんだけど、
ディレクトリ名がelectron/sourcesだとソースコードのほうのelectron/srcと被るから

electron/resources/images/
に変えてもらったほうがいいかも

**Comment by choron634** [comment]
今electron\sources\images\charactersにいれてるよ

**Comment by monado3** [comment]
@choron634 
Thank you for your update.
But it seems that absent.gif no longer exists in the latest your commit...

**Comment by monado3** [comment]
lack of normal avatar gifs
